spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ruleengine
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  sql:
    init:
      mode: never

server:
  port: 8080

logging:
  level:
    com.example.ruleengine: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# CORS configuration
cors:
  allowed-origins: "http://localhost:5173,http://localhost:5174,http://localhost:5175,http://localhost:3000"
  allowed-methods: "GET,POST,PUT,DELETE,PATCH,OPTIONS"
  allowed-headers: "*"
  allow-credentials: true 